### ISSUE TITLE
Get rid of portastic package

### ISSUE THREAD

**Issue by valekjo** [apify/proxy-chain#106]
`portastic` package has been inactive for 5 years, issues have not been adressed for a long time (eg. https://github.com/alanhoff/node-portastic/issues/10) - maybe it would be ok to switch to something else? For example https://www.npmjs.com/package/get-port.

**Comment by jancurn** [comment]
Yeah definitely, actually we don't need it at all, the system can choose free port itself by using port 0.

**Comment by jancurn** [comment]
It's only used in `createTunnel()`, `anonymizeProxy()` already switched to this way few months ago. @valekjo if you're interested in this, feel free to go ahead :)

**Comment by jancurn** [comment]
Will be fixed in https://github.com/apify/proxy-chain/pull/113
