### ISSUE TITLE
Proxies are not rotated when the same request is sent!

### ISSUE THREAD

**Issue by yoyo00xx** [apify/proxy-chain#115]
Right now the request uses the same upstreamProxyUrl every time it happens. 

Different requests got different upstreamProxyUrl but I want it to actually give me different proxies even if the same request is repeated.

This is my code 

const ProxyChain = require('proxy-chain'); 
const proxies = [
    'proxy1',
    'proxy2',
    'proxy3', 
    'proxy4',
    'proxy5',
];
turn = 0;
  const server = new ProxyChain.Server({
    port: 8000,
    prepareRequestFunction: () => {
    const proxy = proxies[turn];
    turn = (turn + 1) % proxies.length
    console.log(proxy)
    return {
    upstreamProxyUrl: proxy,
    };
   },
});
server.listen(() => console.log('Proxy server works!'));

If any one is familiar with this issue please let me know!

Thank you.

**Comment by jancurn** [comment]
If you're using HTTPS from a browser, the browser might reuse the existing connections. Proxy chain only selects a new proxy on a new connection

**Comment by yoyo00xx** [comment]
oh that might be why. is it possible to close connection automatically or no?

**Comment by koteesy** [comment]
> oh that might be why. is it possible to close connection automatically or no?

You need close client connection, then proxy-chain will close connection automatically and get new proxy from list, for example, in Golang you can do something like:

<pre>
cl := &http.Client{}
req, _ := http.NewRequest("GET", "http://httpbin.org/get", nil)

// Will close connection.
req.Close = true

resp, _ := cl.Do(req)

log.Println(resp.statusCode)
</pre>
