### ISSUE TITLE
version rollback 0.49 => 0.47

### ISSUE THREAD

**Issue by rafipiccolo** [apify/proxy-chain#117]
Hello,

i can see here that current version is 0.47
https://www.npmjs.com/package/proxy-chain

this is why npm is now installing version 0.47 by default
but last week it was installing version 0.49.

```
npm install proxy-chain
```

hence my question, why this rollback ?
Should i downgrade ? is there a bug/security risk in 0.49 or 0.48 ?

**Comment by jancurn** [comment]
It was just that the changes introduced in the `parseUrl()` function turned out to be breaking, so we reverted back. All the changes were released in version 1.0 (now in beta).

See https://github.com/apify/proxy-chain/blob/master/CHANGELOG.md

**Comment by rafipiccolo** [comment]
Thx
