### ISSUE TITLE
Get the complete request url

### ISSUE THREAD

**Issue by foodmade** [apify/proxy-chain#120]
I want to get the complete url address from the request parameter of the prepareRequestFunction function, but now I can only get the host and port, how should I get it
![QQ截图20210329163040](https://user-images.githubusercontent.com/15045287/112808968-1f5e9900-90ac-11eb-983c-975babcbbdec.png)

**Comment by jancurn** [comment]
Not possible due to HTTPS encryption, see https://github.com/apify/proxy-chain/issues/118
