### ISSUE TITLE
No TS support

### ISSUE THREAD

**Issue by ali-habibzadeh** [apify/proxy-chain#122]

**Comment by ali-habibzadeh** [comment]
Wanted to use it but its not possible. Will check back in a few months

**Comment by alexandrucancescu** [comment]
You know you can write them yourself and contribute to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) ?

**Comment by ali-habibzadeh** [comment]
The quality/being up to date is never comparable to when a lib is shipped with types.  DefinitelyTyped is always a cat and mouse chase.

**Comment by alexandrucancescu** [comment]
You can't expect every lib author to go the extra mile of writing typings or converting the project to typescript. Also Typescript doesn't improve code cleanliness for everybody, sometimes it get get uglier than vanilla js.

**Comment by jasonswearingen** [comment]
also, you can enable javascript type checking which gives you a lot of the benifits without adding the types explicitly

**Comment by ali-habibzadeh** [comment]
I will show myself out :)
