### ISSUE TITLE
Can't closeTunnel() because `runningServers[port].connections.forEach is not a function`

### ISSUE THREAD

**Issue by OddMorning** [apify/proxy-chain#127]
When trying to `closeTunnel()`, the following error appears:

```
UnhandledPromiseRejectionWarning: TypeError: runningServers[port].connections.forEach is not a function
    at <…>\node_modules\proxy-chain\build\tcp_tunnel_tools.js:130:42
```

---
I suppose that happens because of this line:
https://github.com/apify/proxy-chain/blob/43e8c9d2a2a891217ccee2fc1a3f1115fcc4828b/src/tcp_tunnel_tools.js#L39

Since a server initiates the `connections` key as an array, the line probably should be like this:
```js
runningServers[port].connections.push(srcSocket);
```

**Comment by jancurn** [comment]
Good catch. Any chance you could prepare a PR? If you go for it, pls add a note to CHANGELOG a bump version in package.json, then we can merge it right away. Unit test covering the current issue would be superb.

**Comment by OddMorning** [comment]
Here it is (#128). But I'm not good at tests so I didn't touch them
