### ISSUE TITLE
How Much load can this sustain ? 

### ISSUE THREAD

**Issue by kryptome** [apify/proxy-chain#129]
I am using this on a t3.micro and the server maxes out at around 600ish connections, What's the max someone has used with this? 

I have done the following updates on the UBUNTU server however still didn't help much. 

Increase size of file handles and inode cache
` fs.file-max = 2097152`
Allowed local port range
`net.ipv4.ip_local_port_range = 15000 65535`
Protect Against TCP Time-Wait
` net.ipv4.tcp_rfc1337 = 1`

Lemme know if someone has load tested and was able to go higher.

**Comment by jancurn** [comment]
proxy-chain is very lean, once the connection is established, it just pipes two Node.js sockets together. So you're really looking at the limits of your Node.js and system configuration. So I'm closing this issue since this is not the best place to discuss Node.js network performance.
