### ISSUE TITLE
How to use the CONNECT method

### ISSUE THREAD

**Issue by QuynhVir** [apify/proxy-chain#131]
I don't see any examples.
When I try to access HTTPS sites from this proxy I always receive the message: 
`ProxyServer[14702]: Listening...`
`ProxyServer[14702]: 1 | !!! Handling GET https://api.ipify.org/?format=json HTTP/1.1`
`ProxyServer[14702]: Request failed (status 400): Only HTTP protocol is supported (was https:)`

**Comment by QuynhVir** [comment]
Never mind, it's a bug of Axios.

**Comment by lolyinseo** [comment]
Hoe

> Never mind, it's a bug of Axios.

How do you solve that?

**Comment by QuynhVir** [comment]
> Hoe
> 
> > Never mind, it's a bug of Axios.
> 
> How do you solve that?

use [got](https://www.npmjs.com/package/got) instead

**Comment by Keith-Hon** [comment]
Got the same error using axios
