### ISSUE TITLE
Inspect HTTP Responses

### ISSUE THREAD

**Issue by guifre** [apify/proxy-chain#138]
Hi,

Is it possible to intercept or inspect the HTTP response programmatically before returning it back to the client?

Seems like the onRequest function in server.py handles it, but it doesn't appear to be a simple mechanism to expose that to the client.

Thank you

**Comment by jancurn** [comment]
In principle, you could use the `customResponseFunction`, process the response, transform it and send it back to client.

**Comment by guifre** [comment]
Do you know if  the response buffer available anywhere from the customResponseFunction? It doesn't seem to be the case.

Thank you

**Comment by jancurn** [comment]
It should be available under `this.trgSocket` - see `HandlerCustomResponse` and `HandlerBase` in the source code.

**Comment by guifre** [comment]
Thank you so much. I am almost there I can see cleartext connections data, but for TLS tunnels the data is encrypted and have not figured out how to decrypt it. Any hint?

Thanks
