### ISSUE TITLE
Can we read response statusCode/body?

### ISSUE THREAD

**Issue by koteesy** [apify/proxy-chain#141]
Hello! Thanks for great library, for example, i have pool of proxies, which sometimes contains bad proxies.

For example:

<pre>
const proxies = [
    'http://51.222.21.93:80',
     'http://107.1.80.135:80',
     'http://34.234.164.65:80'
];
</pre>

I'll made request with them, and looks like everything is okay:
<pre>
const proxies = [
      'http://51.222.21.93:80',
      'http://107.1.80.135:80',
      'http://34.234.164.65:80'
];
const usedProxies = {};

const server = new ProxyChain.Server({
  // Port where the server will listen. By default 8000.
  port: 5050,

  // Enables verbose logging
  verbose: true,

  prepareRequestFunction: ({request, username, password, hostname, port, isHttp, connectionId}) => {
    const proxy = proxies[Math.floor(Math.random()*proxies.length)];

    console.log("Use", proxy, connectionId);
    
    usedProxies[connectionId] = proxy;

    return {
      upstreamProxyUrl: proxy,
    };
  },
});
</pre>

But sometimes sites start blocking my proxies, for example, start giving 403 status code, can we process that response for determine what proxies got blocked, and remove them from our proxies pool? Something like:

<pre>
server.on('requestResponse', ({response, connectionId}) => {
  if (response.statusCode === 401) {
    // Remove proxy from list.
    proxies = proxies.filter(e => e !== usedProxies[connectionId]);
  }
});
</pre>

**Comment by jancurn** [comment]
This is not possible for SSL/TLS encrypted connections. For HTTP connections you can do this using the `customResponseFunction`. See also https://github.com/apify/proxy-chain/issues/138
