### ISSUE TITLE
Symbol as a proxyChainId

### ISSUE THREAD

**Issue by thomas510111** [apify/proxy-chain#174]
Using Symbol as proxyChainId is kind of problematic imo.Mostly in cases where you want to store/interfere with connectionIds using some database, since Symbols cant be serialized.  UUID or Incremental ids should suffice.

**Comment by szmarczak** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toString

**Comment by szmarczak** [comment]
It's a number now
