### ISSUE TITLE
anonymizeProxy but with a non-random port?

### ISSUE THREAD

**Issue by gcleaves** [apify/proxy-chain#212]
Hi, I'd like to specify the port when using anonymizeProxy but I don't think it is possible, the port is always chosen at random. Is there a way to start a proxy on a port number I decide?

**Comment by szmarczak** [comment]
No(t yet). Currently it's hard coded in here https://github.com/apify/proxy-chain/blob/29281f6d9591a05fb8837b80a17bd7568fe387c8/src/anonymize_proxy.ts#L33

What's your use case?

**Comment by gcleaves** [comment]
My particular use case was that I was passing the proxy address to workers across multiple different nodes, which open puppeteer using the given proxy. Obviously other nodes can't reach the proxy opened on one node. 

My thought was to open proxies on each node using the same localhost:knownPort pattern. 

There are other ways for me to work around the random port "problem".

**Comment by szmarczak** [comment]
I see, that makes sense. 

https://github.com/apify/proxy-chain/blob/29281f6d9591a05fb8837b80a17bd7568fe387c8/src/anonymize_proxy.ts#L15

could be

```ts
export const anonymizeProxyWithPort = (proxyUrl: string, port: number, callback?: (error: Error | null) => void): Promise<string> => {
```

and we would export `anonymizeProxy` that would call `anonymizeProxy(proxyUrl, 0, callback)`. Would you be up to sending a PR with a test?

**Comment by DanielNetzer** [comment]
@szmarczak I thought on taking the challenge for this PR and was wondering what do you think about this kind of implementation:

```
/**
 * Parses and validates a HTTP proxy URL. If the proxy requires authentication, then the function
 * starts an open local proxy server that forwards to the upstream proxy.
 */
export const anonymizeProxy = (
    options: string | AnonymouseProxyOptions,
    callback?: (error: Error | null) => void
): Promise<string> => {
    let proxyUrl: string;
    let port = 0;

    if (typeof options === "string") {
        proxyUrl = options;
    } else {
        proxyUrl = options.url;
        port = options.port;
    }

    const parsedProxyUrl = new URL(proxyUrl);
    if (parsedProxyUrl.protocol !== "http:") {
        throw new Error(
            'Invalid "proxyUrl" option: only HTTP proxies are currently supported.'
        );
    }
...
```

**Comment by szmarczak** [comment]
That works as well :)

**Comment by DanielNetzer** [comment]
@szmarczak #214
