### ISSUE TITLE
ERR_INVALID_URL with version 2.0.1

### ISSUE THREAD

**Issue by rafipiccolo** [apify/proxy-chain#229]
i use node latest (18.1.0)

this code used to work with version 1.0.4.
but now with latest version (2.0.1) it throws an error : ERR_INVALID_URL

with previous version it was called like this
```
const oldProxyUrl = `[${process.env.PROXY}](http://xxx:xxxxx@xxx.com:3128)`;
const newProxyUrl = await proxyChain.anonymizeProxy(oldProxyUrl);
```

now i adapted like this to follow recent documentation
```
    const oldProxyUrl = `[${process.env.PROXY}](http://xxx:xxxxx@xxx.com:3128)`;
    const newProxyUrl = await proxyChain.anonymizeProxy({ proxyUrl: oldProxyUrl }); // IT THROWS HERE

    const browser = await puppeteer.launch({
        args: ['--no-sandbox', '--disable-setuid-sandbox', `--proxy-server=${newProxyUrl}`],
    });
```

here is the error

"TypeError [ERR_INVALID_URL]: Invalid URL",
"    at new NodeError (node:internal/errors:377:5)",
"    at URL.onParseError (node:internal/url:563:9)",
"    at new URL (node:internal/url:643:5)",
"    at Object.anonymizeProxy (/usr/app/node_modules/proxy-chain/dist/anonymize_proxy.js:26:28)",
"    at trajectoire (file:///usr/app/trajectoire.js:20:42)",
"    at file:///usr/app/server.js:47:26",
"    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)",
"    at next (/usr/app/node_modules/express/lib/router/route.js:144:13)",
"    at Route.dispatch (/usr/app/node_modules/express/lib/router/route.js:114:3)",
"    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)"

any advice ?

**Comment by rafipiccolo** [comment]
it looks like the old way of calling this function still works.

therefore the readme is incorrect and could be corrected like this to at least provide users with a working version :
```
    const oldProxyUrl = 'http://bob:password123@proxy.example.com:8000';
-    const newProxyUrl = await proxyChain.anonymizeProxy({ proxyUrl: oldProxyUrl });
+    const newProxyUrl = await proxyChain.anonymizeProxy(oldProxyUrl);
```

or like this if you prefer the object parameter, but with the later i dont know how to specify the password.
```
-    const oldProxyUrl = 'http://bob:password123@proxy.example.com:8000';
-    const newProxyUrl = await proxyChain.anonymizeProxy({ proxyUrl: oldProxyUrl });
+    const newProxyUrl = await proxyChain.anonymizeProxy({url: 'proxy.example.com', port: 8000});
```

the commit to blame : https://github.com/apify/proxy-chain/commit/c44e9af70b5454e3f712596e589ff5fc1a4209a2

there seem to be no "winning" test associated with this use case of providing an object to the function anonymizeProxy.
The test created have the same typo (proxyUrl instead of url).

**Comment by jancurn** [comment]
CC @DanielNetzer

**Comment by DanielNetzer** [comment]
fixed by https://github.com/apify/proxy-chain/pull/230
