### ISSUE TITLE
Proxy config at page level

### ISSUE THREAD

**Issue by jameshooddisc** [apify/proxy-chain#239]
Is possible to config two different ports with two different upstream proxies and then connect to one or other at per-page level?

Also is possible to provide credentials through authenticate to the proxy chain instead of hardcoding when creating the server ?

Thanks

**Comment by szmarczak** [comment]
> per-page level?

Then it's dependent on the client-side, not the server side. If you connect via TLS then there's no way to know what page you're on.

> Also is possible to provide credentials through authenticate to the proxy chain instead of hardcoding when creating the server ?

Yes, via `prepareRequestFunction`. There's an example in the readme.
