### ISSUE TITLE
Why was connectionClosed emit removed in v2

### ISSUE THREAD

**Issue by jirimoravcik** [apify/proxy-chain#251]
https://github.com/apify/proxy-chain/blob/master/src/server.ts#L468
is missing the code that was present in https://github.com/apify/proxy-chain/blob/cdfbb20b4cd413c44867202735e0237476ae509d/src/server.js#L396

**Comment by szmarczak** [comment]
It's not removed:

https://github.com/apify/proxy-chain/blob/25c12fec1e80383e249aef7e6c3718646f913ecb/src/server.ts#L195

**Comment by jirimoravcik** [comment]
Missed that, the comment is a bit misleading as I'd expect the emit to be close to it

**Comment by jancurn** [comment]
This sounds like the documentation could be improved a bit.
