### ISSUE TITLE
Skips using proxy for certain pages

### ISSUE THREAD

**Issue by adminy** [apify/proxy-chain#259]
I've noticed it only does certain domains proxy forwarding in firefox and not others, any idea why that is? Dns caching?

**Comment by fnesveda** [comment]
Can you share some domains where the proxy forwarding does not work for you, or some reproducible example, so we know where to start looking? Thanks!

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/179442802-11e043ce-a654-4c09-bf20-97a242ff9d93.png)

@adminy I'm not able to reproduce the issue, can you post reproducible code please?
