### ISSUE TITLE
How to get headers from Connect Event

### ISSUE THREAD

**Issue by Benraay** [apify/proxy-chain#30]
Hi I'm using your proxy-chain module for some it works very well with my previous proxy with the anonymize function  but I have a new one : ProxyMesh, 
I need to send some headers only to the proxy and not to the final website, how can I achieve this ?
need to send this header "X-ProxyMesh-Not-IP" 

also I need to get some headers from the proxy after the first call to "connect" on the proxy
I need to get the "X-ProxyMesh-IP"
find more info here: https://docs.proxymesh.com/article/7-request-response-headers#https

whole documentation : https://docs.proxymesh.com/article/7-request-response-headers

I suppose I need to use the prepareRequestFunction but I could not get it working !

I need this on HTTPS final sites  !! the proxy is http

**Comment by Benraay** [comment]
here is a code sample using the raw node http module I hope this helps

`const http = require('http')
const https = require('https')
const username = 'username'
const password = 'password'
const auth = 'Basic ' + Buffer.from(username + ':' + password).toString('base64');

http.request({
     host: 'fr.proxymesh.com', // IP address of proxy server
     port: 31280, // port of proxy server
     method: 'CONNECT',
     path: 'api.ipify.org', // some destination,
     headers: {
         'Host' : "https://api.ipify.org",
         'Proxy-Authorization': auth
         },
     }).on('connect', (res, socket) => {
         if (res.statusCode === 200) { // connected to proxy server
             //get the ip used by proxymesh here
             console.log("IP : "+res.headers["x-proxymesh-ip"]);
             https.get({
                     host: 'api.ipify.org',
                     socket: socket, // using a tunnel
                     agent: false    // cannot use a default agent
                     path: '/' //put here the path ont the target site
             }, (res) => {
                 let chunks = []
                 res.on('data', chunk => chunks.push(chunk));
                 res.on('end', () => {
                         console.log('DONE', Buffer.concat(chunks).toString('utf8'))
                 })
             })
         }
     }).on('error', (err) => {
           console.error('error', err)
     }).end();`

**Comment by Benraay** [comment]
Hi here,

after some investigation I could find where the CONNECT action is done

it's done inside handler_tunnel_chain.js on line 44
the onTrgRequestConnect function returns a response object with the headers I need.

is there an easy way to listen to that event, I don't see any emit on that one, could be great to add some option for emiting that event with headers

**Comment by jancurn** [comment]
Hi @Benraay, so if I understand it correctly, you'd like to pass a custom header to the CONNECT request to the target proxy. It's the following line of code:

https://github.com/apifytech/proxy-chain/blob/master/src/handler_tunnel_chain.js#L28

Correct?

And regarding obtaining headers from the target server, I'm not sure what would be the best way to add support for this. Maybe we could add another event to `Server` class called `targetConnected` that would receive all possible data. What do you think? Another option for you is to add a small hack - override the `HandlerBase.checkUpstreamProxy407` of the handler to get a reference to the `response`.

Anyway, it would be great if you could prepare a pull request with the desired changes and tests, I'll gladly merge this into the code base.

**Comment by Benraay** [comment]
Hi, thank for your reply, yes the headers to be sent are in that position.
for getting the headers I have made a patch on your library adding a few lines of code 
here
https://github.com/apifytech/proxy-chain/blob/master/src/handler_tunnel_chain.js#L53
I have added an event emit : 
`this.emit('onTrgRequestConnect', { response: response, socket:socket, head:head });`

and here 
https://github.com/apifytech/proxy-chain/blob/master/src/server.js#L339
a listener and an event emitter with this I can get the headers I need
```
handler.once('onTrgRequestConnect', ({ response,socket,head }) => {
    this.emit('onTrgRequestConnect', {
        connectionId: handler.id,
        response,
        socket,
        head
    });
});```

//after it's possible to listen to the onTrgRequestConnect event on the server like this
```server.on('onTrgRequestConnect', ({ response, socket, head }) => {
    console.log("proxyIp : "+response.headers['x-proxymesh-ip'])
});
```
maybe when don't need socket and head parameters but if someone else needs to access it, it can be helpful
I'm still making some tests and will make a pull request on that change

another question is there any way to listen on events on an anonymize helper ? if not how can I be sure that the local proxyserver is up ? and restarting it if it has gone.

**Comment by Benraay** [comment]
Hi @jancurn I have added a pull request with the changes I need

**Comment by Raidus** [comment]
Is it possible to override the headers for CONNECT method before sending them to the proxy? I would like to add information of the proxy in the user-agent and then strip the added part from the user-agent before sending them to the proxy.
