### ISSUE TITLE
In version 2.1.0 I get an error that the node:buffer module cannot be found.

### ISSUE THREAD

**Issue by kurohoan** [apify/proxy-chain#327]
"proxy-chain": "^2.1.0",

In version 2.1.0 I get an error that the node:buffer module cannot be found.
What could be the cause?

`
Error: Cannot find module 'node:buffer'
Require stack:
- XXX/node_modules/proxy-chain/dist/utils/parse_authorization_header.js
- XXX/node_modules/proxy-chain/dist/server.js
- XXX/node_modules/proxy-chain/dist/index.js
- XXX/dist_electron/index.js
- XXX/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (XXX/node_modules/proxy-chain/dist/utils/parse_authorization_header.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
`

**Comment by kurohoan** [comment]
I don't require node:buffer, up to version 2.0.5, I don't get any errors, is it an environmental issue?

**Comment by nopaluwu** [comment]
try `apt install node-buffer`, this is work for me

**Comment by primaltalk** [comment]
What version of nodejs are you on?  I had to upgrade.

**Comment by kurohoan** [comment]
i tried 
```
npm i node-buffer
```

The error did not change.

**Comment by kurohoan** [comment]
> What version of nodejs are you on? I had to upgrade.

node.js version is 14.17.6

Is it a version that is not supported?

**Comment by szmarczak** [comment]
Node protocol imports are supported since v14.18.0

**Comment by B4nan** [comment]
> Node protocol imports are supported since v14.18.0

I was hoping TS will downlevel this for us - we specify support for [node v14](https://github.com/apify/proxy-chain/blob/master/package.json#L43-L45), not node v14.18+. Probably better to remove the `node:` prefixed imports for now.

**Comment by nopaluwu** [comment]
> i tried
> 
> ```
> npm i node-buffer
> ```
> 
> The error did not change.

on linux, try this command
`apt-get install node-buffer`, this is will be fix the main problem here

**Comment by B4nan** [comment]
None of the suggestions will fix this, the import is for the node.js native module, not for any third party dependency like `node-buffer`, nor any linux package. The problem is purely about old nodejs versions that do not support `node:` prefixed imports.

**Comment by kurohoan** [comment]
The node.js version was changed to 16.18.0, but the error did not improve.
Node.js was installed with homebrew.

**Comment by kurohoan** [comment]
I am using this module via electron. Does this have anything to do with the symptoms not improving?

**Comment by szmarczak** [comment]
Fixed in `v2.1.1`

**Comment by kurohoan** [comment]
Thank you for your correspondence.
