### ISSUE TITLE
Page loading is slow.

### ISSUE THREAD

**Issue by kurohoan** [apify/proxy-chain#329]
Version 2.0.5 of proxy-chain is used.
I am using this module on praywright, but when using proxy the page loads very slowly and times out if it takes more than 30 seconds.
I use a fast proxy, but I would like the page to load faster.
Could you please give me some tips on how to do this?

**Comment by jancurn** [comment]
Have you tried connecting to your proxy directly, without proxy-chain? Maybe it's slow after all

**Comment by kurohoan** [comment]
The proxy I use is a fast one, and most of the time I get a response within two seconds when I access it with the checking tool.
However, when using the tool I am developing, proxy-chain, it takes over 30 seconds to load the page and times out.

**Comment by jancurn** [comment]
Please try to use your proxy directly from Playwright, without the proxy-chain, to ensure proxy-chain is really the issue. If it works, try to upgrade to latest version of proxy-chain and try again. If the issue persists, please send a code you're using. Closing this in the meantime

**Comment by kurohoan** [comment]
#327 
We are currently facing the above problem, which is why we cannot update to a version newer than 2.0.5.

For the time being I will try to use the proxy directly from playwright.
We will contact you again.

**Comment by jancurn** [comment]
Please upgrade to latest proxy-chain version, the issue has been fixed

**Comment by kurohoan** [comment]
Updated to the latest version, but speeds previously remained slow.
When I set up the proxy using only playwright without proxh-chain as a trial, I could not access the site in the first place.
With proxy-chain, access is still possible.

I am using playwright on electron, is there a connection?
This may be out of place, so I'll start a new issue topic on playwright for once.
