### ISSUE TITLE
Tor network as upstream proxy

### ISSUE THREAD

**Issue by sirramin** [apify/proxy-chain#34]
Can I proxy requests to tor instances?
I'm thinking about using [tor-request](https://www.npmjs.com/package/tor-request)

**Comment by sirramin** [comment]
I convert tor socks proxy to http proxy using [http-proxy-to-socks](http-proxy-to-socks) package and implemented in my app:

```
const server = new ProxyChain.Server({
    port: 8000,
    verbose: true,
    repareRequestFunction: ({ request, username, password, hostname, port, isHttp, connectionId }) => {
        return {
            requestAuthentication: false,
            upstreamProxyUrl: `http://127.0.0.1:8080`
        };
    },
});
```
But the proxy still expose server's public IP address

**Comment by jancurn** [comment]
How does it expose the public IP address? The target website should only see the IP addresses of the last tor peer.

**Comment by szmarczak** [comment]
Duplicate of https://github.com/apify/proxy-chain/issues/69
