### ISSUE TITLE
SOCKS5 support

### ISSUE THREAD

**Issue by bacnt2412** [apify/proxy-chain#373]
Please support socks5
Thank pro

**Comment by jancurn** [comment]
Hopefully we will soon: https://github.com/apify/proxy-chain/pull/370

**Comment by bacnt2412** [comment]
I need to create a proxy server that supports type socks5, not upstream with socks5

**Comment by bacnt2412** [comment]
Server socks5 same library https://github.com/brozeph/simple-socks

**Comment by nosovk** [comment]
It would be nice to have it. There is some forks that could be good starting point - https://github.com/yovanoc/proxy-chain

**Comment by KaptinLin** [comment]
@nosovk looks good @bacnt2412 when support?

**Comment by AkiraWang89** [comment]
Do socks5 work now?

**Comment by raunaqss** [comment]
I agree, this would be helpful.

**Comment by ARNboy** [comment]
Still waiting for this for long time... Please

**Comment by nosovk** [comment]
We added some additional proxy ourselves inside the project, and point browser to it.

**Comment by jancurn** [comment]
We're on it, thanks for your patience

**Comment by ARNboy** [comment]
Thank you so much..

**Comment by arndesk** [comment]
Thank you so much
