### ISSUE TITLE
Introduce command line interface to start a local proxy server connect to upstream

### ISSUE THREAD

**Issue by link89** [apify/proxy-chain#410]
I would like to use `proxy-chain` to start a local proxy server that connected to a upstream proxy. It would be convienient to have a command line interface to doing so for some quick testing. 

It's not a complicated thing to implement such feature. I would like to create a PR for this if you think it is useful.

**Comment by jirimoravcik** [comment]
Hello, thanks for the effort. PRs are always welcome, so feel free to create one. Cheers.

**Comment by link89** [comment]
I think it would be better as a standalone package as it introduces some extra dependencies that are useless to the exited users.
Here is the package: https://www.npmjs.com/package/proxy-chain-cli 

By the way, I find that proxy-chain don't support https protocol for upstream. Is there plan to support this? I would like to do something but I don't have idea about how to make it. It seems much more complicated than the http one.
