### ISSUE TITLE
Issue with latest stable version 2.2.1 and README about customTag

### ISSUE THREAD

**Issue by thejimbow** [apify/proxy-chain#428]
I wanted to use customTag feature, but I found that you haven't really released this feature with v2.2.1 which is the latest version in NPM registry. I couldn't find it in releases in GitHub, but the v2.3.0-beta.0 tag is there. This might be a bit confusing.

**Comment by jancurn** [comment]
cc @jirimoravcik

**Comment by jirimoravcik** [comment]
Hello @thejimbow,
thank you for reporting this. It turns out I forgot to create a proper release for v2.3.0. I just did it now, so 2.3.0 is available in NPM registry.
