### ISSUE TITLE
Error: net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by terion-name** [apify/proxy-chain#43]
I get `Error: net::ERR_SSL_PROTOCOL_ERROR` when trying to access https site via http socket

```
puppeteer.launch({
    headless: true,
    args: [
      `--window-size=${ua.data.viewportWidth},${ua.data.viewportHeight + windowFrame}`,
      `--proxy-server=${await proxyChain.anonymizeProxy(getRandomProxy())}`,
    ]
  }).then(async browser => {
const page = await browser.newPage();
await page.goto('https://some-site.com/'), {waitUntil: 'networkidle0'};
})
```

It seems that error is happening when site has Let'sEncrypt's cert, accessing sites with comodo certs (e.g. https://www.myip.com/) works

**Comment by terion-name** [comment]
verbose:
```
Server[4567]: 1 | !!! Handling CONNECT parimatch-new.com:443 HTTP/1.1
Server[4567]: 1 | Using upstream proxy http://user:<redacted>@<ip-address-here>:9257/
Server[4567]: 1 | Using HandlerTunnelChain
Server[4567]: 1 | Connecting to upstream proxy...
Server[4567]: 1 | Target socket assigned
Server[4567]: 1 | Connected to upstream proxy
Server[4567]: 1 | Target socket ended
Server[4567]: 1 | Target socket closed
(node:16613) UnhandledPromiseRejectionWarning: Error: net::ERR_SSL_PROTOCOL_ERROR at https://some-site.com/

```

**Comment by jancurn** [comment]
Thanks for reporting this, looks like some bug in handling SSL errors. We'll look into it - or pull requests are welcome.

**Comment by jancurn** [comment]
@pocesar It seems you were using the [Apify Proxy](https://apify.cm/proxy)'s GOOGLE_SERP proxy group when running the [Google Places Scraper](https://apify.com/drobnikj/crawler-google-places) actor. Unfortunately, the GOOGLE_SERP proxy group only supports queries to Google Search and Google Shopping, but not to Google Maps. And since you're connecting over SSL (to https://maps.google.com), Apify Proxy has no way to respond back with an error to tell you about this, and the connection only fails with an SSL error like you're getting.

Just make sure you're not using GOOGLE_SERP proxy group, that's all.

**Comment by jancurn** [comment]
@terion-name We've checked it and the Let's Encrypt certificates are normally supported. Perhaps your system didn't have Let's Encrypt in their root certificates? Can you try to connect to the server directly without the proxy to see if the error is still there?

**Comment by jancurn** [comment]
Please, can you test it again with the new release 0.3.2?

**Comment by terion-name** [comment]
@jancurn got a pause with project where this issue occurred, retuning to it, will test soon, thank you

**Comment by wizehood** [comment]
Any update about this?
I get the exact same issue when using proxies with special characters inside the proxy URL (containing password for example etc)

Thanks

**Comment by jancurn** [comment]
@wizehood please can you provide more examples or ideally some sort of reproduction case?

**Comment by wizehood** [comment]
@jancurn 
I'm getting this with my client who got credentials from a 3rd party proxy provider. The provisionary URL goes something like this: `http://customer-marktwain-session-60-sessionid-12345:passw%rd@proxy.cloud:1234`

It seems like special character inside the password creates an issue for this specific proxy string. Note that I didn't have problems before with digit/char/dash mixed passwords before.

**Comment by kemphack** [comment]
Getting this error too while navigating https site

**Comment by bolein** [comment]
Same here
