### ISSUE TITLE
Linux Mint: Invalid upstream proxy credentials

### ISSUE THREAD

**Issue by ZnerAIO** [apify/proxy-chain#470]
I am using user:password protected proxies. Works flawlessly on Windows, but when I run the exact same code on Linux Mint, Proxies dont seem to get authenticated. When I use non-password protected proxies, it works fine. I have also tried disabling firewall and no change.
Does this work on Linux?

**Comment by jancurn** [comment]
Linux is fully supported. Actually, most of the upstream proxies we use in production run on Linux. Please make sure you're running the latest version, and that the proxy configuration is correct. Feel free to share the code too.
