### ISSUE TITLE
Proxy Authentication 407

### ISSUE THREAD

**Issue by borkowsky** [apify/proxy-chain#529]
My proxies configured for IP Auth. This library not supports IP auth for proxies?

**Comment by jirimoravcik** [comment]
Hi, can you please specify what's your problem with example code?
`proxy-chain` can easily work with IP address-based authentication, but I need to know your exact use-case and configuration.

**Comment by borkowsky** [comment]
> Hi, can you please specify what's your problem with example code? `proxy-chain` can easily work with IP address-based authentication, but I need to know your exact use-case and configuration.

I just use proxy-chain like descried in readme, using upstream proxy. But requests fails with 407 Proxy Authentication Error.

**Comment by jirimoravcik** [comment]
Hello @borkowsky,
can you please provide minimal example code to reproduce this issue?
You can e.g. redact your sensitive information with `<USERNAME>:<PASSWORD>` or something.
It's difficult to investigate without having the actual code causing the issue.
Thanks
