### ISSUE TITLE
How to create proxy_local socks5 to proxy_server socks5

### ISSUE THREAD

**Issue by s0ckd3** [apify/proxy-chain#544]
I have seen this message.
 * Client -> Apify (HTTP) -> Upstream (SOCKS) -> Web
 * Client <- Apify (HTTP) <- Upstream (SOCKS) <- Web

So if I need to create a local proxy called socks5 and forward socks5 like that, what do I need?

 * Client -> Apify (SOCKS) -> Upstream (SOCKS) -> Web
 * Client <- Apify (SOCKS) <- Upstream (SOCKS) <- Web

Please guide me

**Comment by jancurn** [comment]
AFAIK the proxy-chain doesn't support exposing local proxy via SOCKS, only SOCKS upstream proxies
