### ISSUE TITLE
proxy headers are using the array index as key

### ISSUE THREAD

**Issue by mschfh** [apify/proxy-chain#547]
The proxy receives headers with an array index as key:

```
CONNECT www.ifconfig.co:443 HTTP/1.1
0: host
1: www.ifconfig.co:443
2: proxy-authorization
3: Basic Zm9vOmJhcg==
Host: 192.168.1.1:1234
Connection: keep-alive
```

expected:
```
CONNECT www.ifconfig.co:443 HTTP/1.1
host: www.ifconfig.co:443
proxy-authorization: Basic Zm9vOmJhcg==
...
```

There was an attempt to fix this in #528, but the PR was abandoned.

**Comment by jirimoravcik** [comment]
Hey, can you please provide full reproduction example and the problem with it? We have been using the array structure for headers and it has been working for us.
