### ISSUE TITLE
SOCKS Authentication fails for CONNECT if username contains special characters

### ISSUE THREAD

**Issue by mschfh** [apify/proxy-chain#548]
SOCKS authentication fails for CONNECT requests when the username contains a `@`:

```
proxyChain.anonymizeProxy({url: "socks5://foo@bar.baz:hunter2@example.com:1080", port: 12345})
```

For a HTTP request, everything works as expected (the username is sent as-is).
```
curl -v --proxy 'http://127.0.0.1:12345' 'http://ifconfig.co'
```
<img width="230" alt="image" src="https://github.com/user-attachments/assets/27f6d0f2-fd63-4ebb-b933-4e03be84d514">

For a HTTPS / CONNECT request, the username sent to the upstream SOCKS5 proxy is URL escaped (e.g. `foo%40bar.baz`, as seen in a packet capture) and the SOCKS authentication request fails due to incorrect credentials, the proxy returns a `597` error.

```
curl -v --proxy 'http://127.0.0.1:12345' 'https://ifconfig.co'
```
<img width="252" alt="image" src="https://github.com/user-attachments/assets/a3014ccc-8818-437e-aa24-17d929fccf05">

**Comment by jirimoravcik** [comment]
Fixed in #550
