### ISSUE TITLE
ERR_TUNNEL_CONNECTION_FAILED error when executing with Bun

### ISSUE THREAD

**Issue by cleiltonoliveira** [apify/proxy-chain#553]
I'm having trouble running code with Bun instead of Node.js.
All requests result in net::ERR_TUNNEL_CONNECTION_FAILED error when running with Bun, but when using Node everything is fine. Adding some detailed logs I was able to see some difference in the printed logs:
Running with Bun:
ProxyServer[8000]: 6 | !!! Handling CONNECT  api.ipify.org:443 HTTP/1.1
ProxyServer[8000]: 6 | Using upstream proxy http://package-10001-country-br:<redacted>@rotating.proxyempire.io:5000/
ProxyServer[8000]: 6 | Using forward()

Running with Node:
ProxyServer[8000]: 3 | !!! Handling CONNECT api.ipify.org:443 HTTP/1.1
ProxyServer[8000]: 3 | Using upstream proxy http://package-10001-country-br:<redacted>@rotating.proxyempire.io:5000/
ProxyServer[8000]: 3 | Using chain() => api.ipify.org:443

My question is: why is this occurring? Could there be a problem with Bun? Why does running with Bun result in the forward method?
Could anyone help with this?

**Comment by jancurn** [comment]
Bun is not officially supported yet, but it would be awesome if you helped us support it by sending a pull request :)
