### ISSUE TITLE
https relay proxy support

### ISSUE THREAD

**Issue by arenevier** [apify/proxy-chain#563]
When trying to connect to a https proxy, I get the following error:
`Invalid "upstreamProxyUrl" provided: URL must have one of the following protocols: "http", "socks", "sock4", "socks4a", "socks5", "socks5h"`

Here is a minimal example to reproduce:
```
import * as ProxyChain from 'proxy-chain';
  
  async function main() {
  
    const server = new ProxyChain.Server({
      port: 6000,
      host: '127.0.0.1',
     prepareRequestFunction: (params) => { 
            return {
              upstreamProxyUrl: "https://some.https.proxy"
            };
      },
    });
  
  }
  
  main();
```

**Comment by jirimoravcik** [comment]
Fixed in version `2.5.6`.
