### ISSUE TITLE
Proxies Hang When sending concurrent requests with upstream proxy & local proxy

### ISSUE THREAD

**Issue by basky12** [apify/proxy-chain#60]
Having an issue where inbound requests are being received by proxy-chain, when submitting multiple requests to the upstream proxy there is a massive delay. This only happens when using about 100 - 200 requests. Using lower requests i can get response delay down to a 1-3 seconds but anymore and delay turns to about 10 - 50 seconds. Tried using local proxy-chains http proxy to rule out any rate limits set by proxy provider, issue still exists.

Script otherwise is very powerful.

**Comment by jancurn** [comment]
This is quite strange, we use `proxy-chain` package for hundreds of parallel connections, without any slowdown. Any chance you could share your code to reproduce this issue? Are you using the latest version?

**Comment by basky12** [comment]
Yes, I have tried using base install with example code provided under "Run a simple HTTP/HTTPS proxy server" it still times out if many requests are sent at the same time. Latest version is also being used.

**Comment by tenkuken** [comment]
> Yes, I have tried using base install with example code provided under "Run a simple HTTP/HTTPS proxy server" it still times out if many requests are sent at the same time. Latest version is also being used.

How many CPU and memory do u have?
