### ISSUE TITLE
IPV6 not supported

### ISSUE THREAD

**Issue by petrpatek** [apify/proxy-chain#67]
It seems that IPV6 is not supported now.
`ProxyServer[8883]: 9 | !!! Closed and removed from server
ProxyServer[8883]: 10 | !!! Handling CONNECT [2a00:1450:4014:80c::200a]:443 HTTP/1.1
ProxyServer[8883]: Request failed (status 400): Target "[2a00:1450:4014:80c::200a]:443" could not be parsed`.

**Comment by andretunes** [comment]
Hello!

Can you try do like the Issue #89?

**Comment by jancurn** [comment]
Should be fixed in https://github.com/apify/proxy-chain/pull/103
