### ISSUE TITLE
Can't see all headers

### ISSUE THREAD

**Issue by abacaj** [apify/proxy-chain#74]
Under `prepareRequestFunction`, when examining `http.IncomingMessage.rawHeaders`

The only headers available are host, proxy-connection, user-agent.

Examining the real headers we see that there are many missing, including:
ACCEPT, ACCEPT-ENCODING, ACCEPT-LANGUAGE, UPGRADE-INSECURE-REQUESTS

Any idea how we can see all headers on the proxy?

**Comment by r1si** [comment]
me too
