### ISSUE TITLE
prepareRequestFunction() sometimes have request.socket.remoteAddress undefined

### ISSUE THREAD

**Issue by jancurn** [apify/proxy-chain#80]
When the client connection is closed too early, the `request` object passed to `prepareRequestFunction()` has `socket.remoteAddress` undefined, which can cause issues to users to the proxy-chain package. Since such connections are dead anyway, we should not pass them to `prepareRequestFunction()` and drop them right away.

For details why this happens, see https://github.com/nodejs/node/issues/23858

**Comment by szmarczak** [comment]
Attempting to fix this in 3106aee510c171bd0b95adb42fe6785348c25f32, after the first check we cannot reliably detect socket close since the address is cached and `socket.readyState` is `open`.

**Comment by jancurn** [comment]
Thanks!
