### ISSUE TITLE
How can I change the proxy if the current proxy is not responding?

### ISSUE THREAD

**Issue by tradua** [apify/proxy-chain#83]
I have a code:

```
const server = new ProxyChain.Server({
    port: 8011,
    verbose: true,
    timeout: 5000,
    proxyTimeout: 5000,
    prepareRequestFunction: ({ request, username, password, hostname, port, isHttp, connectionId }) => {
        return {
            upstreamProxyUrl: getRandomProxy(),
        };
    }
});
```
Sometimes I get an error from my proxy and want to replace it with another one. How can i do this?

**Comment by jancurn** [comment]
The upstream proxy cannot be replaced on-the-fly for existing connections. If the upstream proxy fails, just close the connection, and next time when `prepareRequestFunction()` is called for the next request, just pick another proxy.

**Comment by jancurn** [comment]
Closing this since this is not really a bug or issue.
