### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by wizehood** [apify/proxy-chain#89]
I'm getting following exception when using proxy (`http://USERNAME:PASSWORD@HOST:PORT`) with special characters inside (containing password with percentage(%) for example etc). 

```
Failed to open Puppeteer browser. URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Url.parse (url.js:343:19)
    at Object.urlParse [as parse] (url.js:154:13)
    at parseUrl (\node_modules\proxy-chain\build\tools.js:74:32)
    at Object.anonymizeProxy (\node_modules\proxy-chain\build\anonymize_proxy.js:24:46)
    at Crawler.openBrowser (\src\puppeteer.js:42:42)
```
How can we fix this?
Cheers

**Comment by andretunes** [comment]
Hello!

I changed a part of code and sended a Pull Request #102, if you wanna fix it in your side until the release, please open the file `node_modules\proxy-chain\build\tools.js` and do this:
1. On line 73, please replace `_url2.default.parse` to `new URL`.

If you have any questions or need more help, please let me know.

Kind regards,
André

**Comment by wizehood** [comment]
Thanks for the info.

> Hello!
> 
> I changed a part of code and sended a Pull Request #102, if you wanna fix it in your side until the release, please open the file `node_modules\proxy-chain\build\tools.js` and do this:
> 
> 1. On line 73, please replace `_url2.default.parse` to `new URL`.
> 
> If you have any questions or need more help, please let me know.
> 
> Kind regards,
> André

**Comment by wizehood** [comment]
Leaving the issue open until checked..

**Comment by valekjo** [comment]
Hi, this will need some more checking, as the `URL` object does not correspond 1-1 to the old one (returned by `url.parse()`). I'll look into it.

**Comment by jancurn** [comment]
> Hi, this will need some more checking, as the `URL` object does not correspond 1-1 to the old one (returned by `url.parse()`). I'll look into it.

@valekjo I already started on that, but didn't manage to finish it. Perhaps you could take it over? https://github.com/apify/proxy-chain/pull/103

**Comment by jancurn** [comment]
Fixed in https://github.com/apify/proxy-chain/pull/103
