### ISSUE TITLE
closeTunnel always returns false?

### ISSUE THREAD

**Issue by killingcode** [apify/proxy-chain#90]
Sample code below is very similar to [example](https://gist.github.com/gippy/dfbee59d868edc0d074e81bb112f5bef#file-simple-service-tunneling-js) listed on [apify blog](https://blog.apify.com/tunneling-arbitrary-protocols-over-http-proxy-with-static-ip-address-b3a2222191ff).

```

const { createTunnel, closeTunnel } = require('proxy-chain');

(async() => {

    const tunnelInfo = await createTunnel(
        'http://aaa:bbbb@127.0.0.1:8888',
        '127.0.0.2:8889'
    );

    closeTunnel(tunnelInfo).then(res=>console.log(res));
})();
```

No matter what I use as proxyUrl and targetHost result is same - closeTunnel return false but `lsof -i -P -n` show that port is still listening and I can use it as proxy. Am I missing something?

Tested on nodejs version 10.20.1 and 12.19.0, proxy-chain version 0.4.5

**Comment by andretunes** [comment]
Hello!

I changed a part of code and sended a Pull Request #101, if you wanna fix it in your side until the release, please open the file `node_modules\proxy-chain\build\tcp_tunnel_tools.js` and do this:
1. On line 123, please replace `resolve()` to `resolve(true)`, and do the same in the line 127;
2. On line 131, please replace `runningServers[port].close` to `runningServers[port].server.close`.

If you have any questions or need more help, please let me know.

Kind regards,
André

**Comment by jancurn** [comment]
PR merged!
