### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by kemphack** [apify/proxy-chain#96]
ProxyServer[25762]: 63 | Using upstream proxy http://creds@proxy proxy_address/
ProxyServer[25762]: 63 | Using HandlerForward
ProxyServer[25762]: 63 | Connecting to upstream proxy proxy_address
ProxyServer[25762]: 63 | Target socket assigned
ProxyServer[25762]: 61 | Connected to upstream proxy
ProxyServer[25762]: 61 | Target socket ended
ProxyServer[25762]: 61 | Target socket finished
ProxyServer[25762]: 61 | Target socket closed
ProxyServer[25762]: 61 | Source socket finished
ProxyServer[25762]: 61 | Closing handler
ProxyServer[25762]: 61 | !!! Closed and removed from server
ProxyServer[25762]: 63 | Received response from target (502)
ProxyServer[25762]: 63 | Target socket ended
ProxyServer[25762]: 63 | Source response finished, ending source socket
ProxyServer[25762]: 63 | Target socket closed
ProxyServer[25762]: 63 | Source socket finished
ProxyServer[25762]: 63 | Closing handler
ProxyServer[25762]: 63 | !!! Closed and removed from server

**Comment by jancurn** [comment]
This error from the target server:

```
ProxyServer[25762]: 63 | Received response from target (502)
```

Not a bug.
